from ..webapp import db
from .professor import Professor
from .turma import Turma
from .estudante import Estudante
from .matricula import association_table
from .aula import Aula
from .presenca import  Presenca
from .questao import Questao
from .questao_multipla_escolha import QuestaoMultiplaEscolha
from .exame import Exame
from .questao_exame import QuestaoExame
from .resposta_questao_exame import RespostaQuestaoExame
from .notas_exame import NotasExames