from ..webapp import db
from .estudante import Estudante
from .aula import Aula
from .professor import Professor
from .turma import Turma
from .presenca import  Presenca
from .matricula import association_table
from .questao import Questao
from .questao_multipla_escolha import QuestaoMultiplaEscolha
from .exame import Exame
from .questao_exame import questao_exame
from .notas_exame import NotasExames
from .resposta_questao_exame import RespostaQuestaoExame